Added checkout options for release and hotfix

diff --git a/git-flow-hotfix b/git-flow-hotfix
--- a/git-flow-hotfix
+++ b/git-flow-hotfix
@@ -47,6 +47,7 @@ usage() {
 	OPTIONS_SPEC="\
 git flow hotfix [list]
 git flow hotfix start
+git flow hotfix checkout
 git flow hotfix finish
 git flow hotfix publish
 git flow hotfix delete
@@ -361,6 +362,28 @@ showcommands!     Show git commands while executing them
 	echo "- A new remote tracking branch '$BRANCH' was created"
 	echo "- You are now on branch '$BRANCH'"
 	echo
+}
+
+cmd_checkout() {
+	OPTIONS_SPEC="\
+git flow hotfix checkout [-h] <name>
+
+Switch to hotfix branch <name>
+--
+h,help!          Show this help
+showcommands!    Show git commands while executing them
+"
+	# Parse arguments
+	parse_args "$@"
+
+	gitflow_require_version_arg
+
+	git_do checkout "$BRANCH"  || die "Could not check out branch '$BRANCH'."
+}
+
+cmd_co() {
+	# Alias for checkout
+	cmd_checkout "$@"
 }
 
 cmd_finish() {
diff --git a/git-flow-release b/git-flow-release
--- a/git-flow-release
+++ b/git-flow-release
@@ -357,6 +357,7 @@ usage() {
 		OPTIONS_SPEC="\
 git flow release [list]
 git flow release start
+git flow release checkout
 git flow release finish
 git flow release publish
 git flow release track
@@ -548,6 +549,28 @@ v,verbose!           Verbose (more) output
   if flag publish; then
     cmd_publish $NAME
   fi
+}
+
+cmd_checkout() {
+	OPTIONS_SPEC="\
+git flow release checkout [-h] <name>
+
+Switch to release branch <name>
+--
+h,help!          Show this help
+showcommands!    Show git commands while executing them
+"
+	# Parse arguments
+	parse_args "$@"
+
+	gitflow_require_version_arg
+
+	git_do checkout "$BRANCH"  || die "Could not check out branch '$BRANCH'."
+}
+
+cmd_co() {
+	# Alias for checkout
+	cmd_checkout "$@"
 }
 
 cmd_finish() {
