Implemented story action. Stories are sub-features. Removed develop branch references as there is now a develop branch for each feature. Updates to support this mentality.

diff --git a/git-flow-hotfix b/git-flow-hotfix
--- a/git-flow-hotfix
+++ b/git-flow-hotfix
@@ -169,14 +169,17 @@ Start new hotfix branch named <version>, optionally base it on <base> instead of
 h,help!           Show this help
 showcommands!     Show git commands while executing them
 F,[no]fetch       Fetch from origin before performing local operation
+[no]publish        Publish this release after it is started
 "
 	local base
 
 	# Define flags
 	DEFINE_boolean 'fetch' false "fetch from $ORIGIN before performing finish" F
+  DEFINE_boolean 'publish' true "publish this release after it is started"
 
 	# Override defaults with values from config
 	gitflow_override_flag_boolean   "hotfix.start.fetch"   "fetch"
+  gitflow_override_flag_boolean   "release.start.publish" "publish"
 
 	# Parse arguments
 	parse_args "$@"
@@ -231,6 +234,11 @@ F,[no]fetch       Fetch from origin before performing local operation
 	echo
 	echo "     git flow hotfix finish '$VERSION'"
 	echo
+
+  # Keeping both branches implies the --keep flag to be true.
+  if flag publish; then
+    cmd_publish $NAME
+  fi
 }
 
 cmd_publish() {
@@ -307,7 +315,7 @@ p,[no]preserve-merges  Preserve merges
 	fi
 
 	BASE_BRANCH=$(gitflow_config_get_base_branch $BRANCH)
-	BASE_BRANCH=${BASE_BRANCH:-$DEVELOP_BRANCH}
+	BASE_BRANCH=${BASE_BRANCH:-$MASTER_BRANCH}
 
 	warn "Will try to rebase '$NAME' which is based on '$BASE_BRANCH'..."
 	require_clean_working_tree
@@ -374,7 +382,6 @@ k,[no]keep            Keep branch after performing finish
 [no]keeplocal         Keep the local branch
 D,[no]force_delete    Force delete hotfix branch after finish
 n,[no]notag           Don't tag this hotfix
-b,[no]nobackmerge     Don't back-merge master, or tag if applicable, in develop
 "
 	local opts commit keepmsg remotebranchdeleted localbranchdeleted
 
@@ -384,13 +391,12 @@ b,[no]nobackmerge     Don't back-merge master, or tag if applicable, in develop
 	DEFINE_string  'signingkey' "" "use the given GPG-key for the digital signature (implies -s)" u
 	DEFINE_string  'message' "" "use the given tag message" m
 	DEFINE_string  'messagefile' "" "use the contents of the given file as tag message" f
-	DEFINE_boolean 'push' false "push to $ORIGIN after performing finish" p
+	DEFINE_boolean 'push' true "push to $ORIGIN after performing finish" p
 	DEFINE_boolean 'keep' false "keep branch after performing finish" k
 	DEFINE_boolean 'keepremote' false "keep the remote branch"
 	DEFINE_boolean 'keeplocal' false "keep the local branch"
 	DEFINE_boolean 'force_delete' false "force delete hotfix branch after finish" D
 	DEFINE_boolean 'notag' false "don't tag this hotfix" n
-	DEFINE_boolean 'nobackmerge' false "don't back-merge $MASTER_BRANCH, or tag if applicable, in $DEVELOP_BRANCH " b
 
 	# Override defaults with values from config
 	gitflow_override_flag_boolean   "hotfix.finish.fetch"          "fetch"
@@ -401,7 +407,6 @@ b,[no]nobackmerge     Don't back-merge master, or tag if applicable, in develop
 	gitflow_override_flag_boolean   "hotfix.finish.keeplocal"      "keeplocal"
 	gitflow_override_flag_boolean   "hotfix.finish.force-delete"   "force_delete"
 	gitflow_override_flag_boolean   "hotfix.finish.notag"          "notag"
-	gitflow_override_flag_boolean   "hotfix.finish.nobackmerge"    "nobackmerge"
 	gitflow_override_flag_string    "hotfix.finish.signingkey"     "signingkey"
 	gitflow_override_flag_string    "hotfix.finish.message"        "message"
 	gitflow_override_flag_string    "hotfix.finish.messagefile"    "messagefile"
@@ -445,7 +450,6 @@ b,[no]nobackmerge     Don't back-merge master, or tag if applicable, in develop
 	# Update local branches with remote branches
 	if flag fetch; then
 		git_fetch_branch "$ORIGIN" "$BASE_BRANCH"
-		[ "$BASE_BRANCH" = "$MASTER_BRANCH" ] && git_fetch_branch "$ORIGIN" "$DEVELOP_BRANCH"
 	fi
 
 	# Check if the local branches have all the commits from the remote branches
@@ -454,34 +458,6 @@ b,[no]nobackmerge     Don't back-merge master, or tag if applicable, in develop
 	fi
 	if git_remote_branch_exists "$ORIGIN/$BASE_BRANCH"; then
 		require_branches_equal "$BASE_BRANCH" "$ORIGIN/$BASE_BRANCH"
-	fi
-	if [ "$BASE_BRANCH" = "$MASTER_BRANCH" ]; then
-		if git_remote_branch_exists "$ORIGIN/$DEVELOP_BRANCH"; then
-			require_branches_equal "$DEVELOP_BRANCH" "$ORIGIN/$DEVELOP_BRANCH"
-		fi
-	fi
-
-	# If the branch is already merged there is no need to check the hotfix branch
-	# This can happen when the merge in develop fails and we rerun the finish.
-	if ! git_is_branch_merged_into "$BRANCH" "$BASE_BRANCH"; then
-		# Check if the hotfix branch:
-		# - has commits: No reason to finish a hotfix without commits
-		# - Is ahead of the BASE: If it's not a good idea to merge
-		# - Can be merged: If there's no common ancestor we can't merge the hotfix
-		git_compare_refs "$BRANCH" "$BASE_BRANCH"
-		case $? in
-		0)
-			die "You need some commits in the hotfix branch '$BRANCH'"
-			;;
-		1)
-			die "The hotfix branch '$BRANCH' is not ahead of branch '$BASE_BRANCH'"
-			;;
-		4)
-			die "The hotfix branch '$BRANCH' has no common ancestor with branch '$BASE_BRANCH'"
-			;;
-		*)
-			;;
-		esac
 	fi
 
 	if noflag notag; then
@@ -498,8 +474,8 @@ b,[no]nobackmerge     Don't back-merge master, or tag if applicable, in develop
 	# Try to merge into BASE.
 	# In case a previous attempt to finish this release branch has failed,
 	# but the merge into BASE was successful, we skip it now
+	git_do checkout "$BASE_BRANCH" || die "Could not check out branch '$BASE_BRANCH'."
 	if ! git_is_branch_merged_into "$BRANCH" "$BASE_BRANCH"; then
-		git_do checkout "$BASE_BRANCH" || die "Could not check out branch '$BASE_BRANCH'."
 		git_do merge --no-ff "$BRANCH" || die "There were merge conflicts."
 		# TODO: What do we do now?
 	fi
@@ -525,38 +501,6 @@ b,[no]nobackmerge     Don't back-merge master, or tag if applicable, in develop
 		fi
 	fi
 
-	if [ "$BASE_BRANCH" = "$MASTER_BRANCH" ]; then
-		# By default we back-merge the $MASTER_BRANCH unless the user explicitly
-		# stated not to do a back-merge, in that case we use the $BRANCH.
-		if noflag nobackmerge; then
-			MERGE_BRANCH="$BASE_BRANCH"
-		else
-			MERGE_BRANCH="$BRANCH"
-		fi
-
-		# Try to merge into develop.
-		# In case a previous attempt to finish this release branch has failed,
-		# but the merge into develop was successful, we skip it now
-		if ! git_is_branch_merged_into "$MERGE_BRANCH" "$DEVELOP_BRANCH"; then
-			git_do checkout "$DEVELOP_BRANCH" || die "Could not check out branch '$DEVELOP_BRANCH'."
-
-			if noflag nobackmerge; then
-				# Accounting for 'git describe', if a release is tagged
-				# we use the tag commit instead of the branch.
-				if noflag notag; then
-					commit="$VERSION_PREFIX$VERSION"
-				else
-					commit="$BASE_BRANCH"
-				fi
-			else
-				commit="$BRANCH"
-			fi
-
-			git_do merge --no-ff "$commit" || die "There were merge conflicts."
-			# TODO: What do we do now?
-		fi
-	fi
-
 	run_post_hook "$VERSION_PREFIX$VERSION" "$ORIGIN" "$BRANCH"
 
 	# Delete branch
@@ -571,9 +515,6 @@ b,[no]nobackmerge     Don't back-merge master, or tag if applicable, in develop
 
 		# Delete local after remote to avoid warnings
 		if noflag keeplocal; then
-			if [ "$BRANCH" = "$(git_current_branch)" ]; then
-				git_do checkout "$DEVELOP_BRANCH" || die "Could not check out branch '$DEVELOP_BRANCH'."
-			fi
 			if flag force_delete; then
 				git_do branch -D "$BRANCH" && localbranchdeleted=$FLAGS_TRUE
 			else
@@ -589,9 +530,6 @@ b,[no]nobackmerge     Don't back-merge master, or tag if applicable, in develop
 	fi
 
 	if flag push; then
-		if [ "$BASE_BRANCH" = "$MASTER_BRANCH" ]; then
-			git_do push "$ORIGIN" "$DEVELOP_BRANCH" || die "Could not push branch '$DEVELOP_BRANCH' to remote '$ORIGIN'."
-		fi
 		git_do push "$ORIGIN" "$BASE_BRANCH" || die "Could not push branch '$BASE_BRANCH' to remote '$ORIGIN'."
 		if noflag notag; then
 			git_do push --tags "$ORIGIN" || die "Could not push tags to remote '$ORIGIN'."
@@ -606,11 +544,6 @@ b,[no]nobackmerge     Don't back-merge master, or tag if applicable, in develop
 	echo "- Hotfix branch '$BRANCH' has been merged into '$BASE_BRANCH'"
 	if noflag notag; then
 		echo "- The hotfix was tagged '$VERSION_PREFIX$VERSION'"
-	fi
-	if [ "$BASE_BRANCH" = "$MASTER_BRANCH" ]; then
-		[ "$commit" = "$BASE_BRANCH" ] && echo "- Master branch '$BASE_BRANCH' has been back-merged into '$DEVELOP_BRANCH'"
-		[ "$commit" = "$VERSION_PREFIX$VERSION" ] && echo "- Hotfix tag '$VERSION_PREFIX$VERSION' has been back-merged into '$DEVELOP_BRANCH'"
-		[ "$commit" = "$BRANCH" ] && echo "- Hotfix branch '$BRANCH' has been merged into '$DEVELOP_BRANCH'"
 	fi
 	if noflag keep; then
 		if [ $localbranchdeleted -eq $FLAGS_TRUE ]; then
@@ -631,11 +564,7 @@ b,[no]nobackmerge     Don't back-merge master, or tag if applicable, in develop
 	fi
 	echo "- Hotfix branch '$BRANCH' "$keepmsg
 	if flag push; then
-		if [ "$BASE_BRANCH" = "$MASTER_BRANCH" ]; then
-			echo "- '$DEVELOP_BRANCH', '$BASE_BRANCH' and tags have been pushed to '$ORIGIN'"
-		else
-			echo "- '$BASE_BRANCH' and tags have been pushed to '$ORIGIN'"
-		fi
+		echo "- '$BASE_BRANCH' and tags have been pushed to '$ORIGIN'"
 	fi
 	echo "- You are now on branch '$(git_current_branch)'"
 	echo
@@ -680,7 +609,7 @@ r,[no]remote          Delete remote branch
 		git_do checkout "$MASTER_BRANCH" || die "Could not check out branch '$MASTER_BRANCH'."
 	fi
 
-	if ( git_is_branch_merged_into "$BRANCH" "$MASTER_BRANCH" && git_is_branch_merged_into "$BRANCH" "$DEVELOP_BRANCH" ); then
+	if ( git_is_branch_merged_into "$BRANCH" "$MASTER_BRANCH" ); then
 		git_do branch -d "$BRANCH" || die "Could not delete the $BRANCH."
 		if flag remote; then
 			git_do push "$ORIGIN" :"$BRANCH" || die "Could not delete the remote $BRANCH in $ORIGIN."
@@ -692,7 +621,7 @@ r,[no]remote          Delete remote branch
 				git_do push "$ORIGIN" :"$BRANCH" || die "Could not delete the remote $BRANCH in $ORIGIN."
 			fi
 		else
-			die "Hotfix branch '$BRANCH' has been not been merged in branch '$MASTER_BRANCH' and/or branch '$DEVELOP_BRANCH'. Use -f to force the deletion."
+			die "Hotfix branch '$BRANCH' has been not been merged in branch '$MASTER_BRANCH'. Use -f to force the deletion."
 		fi
 	fi
 
diff --git a/git-flow-release b/git-flow-release
--- a/git-flow-release
+++ b/git-flow-release
@@ -37,9 +37,9 @@
 
 #
 # Function used by finish command to actually finish the release branch
-# Called when the base of the release is the $DEVELOP_BRANCH
+# Called when the base of the release is the $MASTER_BRANCH
 #
-_finish_from_develop() {
+_finish_from_master() {
 	local opts merge_branch commit keepmsg remotebranchdeleted localbranchdeleted
 
 	remotebranchdeleted=$FLAGS_FALSE
@@ -48,7 +48,6 @@ _finish_from_develop() {
 	# Update local branches with remote branches
 	if flag fetch; then
 		git_fetch_branch "$ORIGIN" "$MASTER_BRANCH"
-		git_fetch_branch "$ORIGIN" "$DEVELOP_BRANCH"
 	fi
 
 	# Check if the local branches have all the commits from the remote branches
@@ -57,9 +56,6 @@ _finish_from_develop() {
 	fi
 	if git_remote_branch_exists "$ORIGIN/$MASTER_BRANCH"; then
 		require_branches_equal "$MASTER_BRANCH" "$ORIGIN/$MASTER_BRANCH"
-	fi
-	if git_remote_branch_exists "$ORIGIN/$DEVELOP_BRANCH"; then
-		require_branches_equal "$DEVELOP_BRANCH" "$ORIGIN/$DEVELOP_BRANCH"
 	fi
 
 	if noflag notag; then
@@ -116,33 +112,6 @@ _finish_from_develop() {
 		merge_branch="$BRANCH"
 	fi
 
-	# Try to merge into develop.
-	# In case a previous attempt to finish this release branch has failed,
-	# but the merge into develop was successful, we skip it now
-	if ! git_is_branch_merged_into "$merge_branch" "$DEVELOP_BRANCH"; then
-		git_do checkout "$DEVELOP_BRANCH" || die "Could not check out branch '$DEVELOP_BRANCH'."
-
-		if noflag nobackmerge; then
-			# Accounting for 'git describe', if a release is tagged
-			# we use the tag commit instead of the branch.
-			if noflag notag; then
-				commit="$VERSION_PREFIX$VERSION"
-			else
-				commit="$MASTER_BRANCH"
-			fi
-		else
-			commit="$BRANCH"
-		fi
-
-		if noflag squash; then
-			git_do merge --no-ff "$commit" || die "There were merge conflicts." # TODO: What do we do now?
-		else
-			git_do merge --squash "$commit" || die "There were merge conflicts." # TODO: What do we do now?
-			flag squash_info && gitflow_create_squash_message "Merged release branch '$BRANCH'" "$DEVELOP_BRANCH" "$BRANCH" > "$DOT_GIT_DIR/SQUASH_MSG"
-			git_do commit
-		fi
-	fi
-
 	run_post_hook "$VERSION_PREFIX$VERSION" "$ORIGIN" "$BRANCH"
 
 	# Delete branch
@@ -179,7 +148,6 @@ _finish_from_develop() {
 	fi
 
 	if flag push; then
-		git_do push "$ORIGIN" "$DEVELOP_BRANCH" || die "Could not push branch '$DEVELOP_BRANCH' to remote '$ORIGIN'."
 		git_do push "$ORIGIN" "$MASTER_BRANCH" || die "Could not push branch '$MASTER_BRANCH' to remote '$ORIGIN'."
 		if noflag notag; then
 			git_do push --tags "$ORIGIN" || die "Could not push tags to remote '$ORIGIN'."
@@ -195,9 +163,6 @@ _finish_from_develop() {
 	if noflag notag; then
 		echo "- The release was tagged '$VERSION_PREFIX$VERSION'"
 	fi
-	[ "$commit" = "$MASTER_BRANCH" ] && echo "- Master branch '$MASTER_BRANCH' has been back-merged into '$DEVELOP_BRANCH'"
-	[ "$commit" = "$VERSION_PREFIX$VERSION" ] && echo "- Release tag '$VERSION_PREFIX$VERSION' has been back-merged into '$DEVELOP_BRANCH'"
-	[ "$commit" = "$BRANCH" ] && echo "- Release branch '$BRANCH' has been merged into '$DEVELOP_BRANCH'"
 
 	if noflag keep; then
 		if [ $localbranchdeleted -eq $FLAGS_TRUE ]; then
@@ -219,7 +184,7 @@ _finish_from_develop() {
 	echo "- Release branch '$BRANCH' "$keepmsg
 
 	if flag push; then
-		echo "- '$DEVELOP_BRANCH', '$MASTER_BRANCH' and tags have been pushed to '$ORIGIN'"
+		echo "- '$MASTER_BRANCH' and tags have been pushed to '$ORIGIN'"
 	fi
 	echo "- You are now on branch '$(git_current_branch)'"
 	echo
@@ -227,7 +192,7 @@ _finish_from_develop() {
 
 #
 # Function used by finish command to actually finish the release branch
-# Called when the base of the release is NOT the $DEVELOP_BRANCH
+# Called when the base of the release is NOT the $MASTER_BRANCH
 #
 
 _finish_base() {
@@ -285,9 +250,9 @@ _finish_base() {
 
 	merge_branch="$BRANCH"
 
-	# Try to merge into develop.
+	# Try to merge into master.
 	# In case a previous attempt to finish this release branch has failed,
-	# but the merge into develop was successful, we skip it now
+	# but the merge into master was successful, we skip it now
 	if ! git_is_branch_merged_into "$merge_branch" "$BASE_BRANCH"; then
 		git_do checkout "$BASE_BRANCH" || die "Could not check out branch '$BASE_BRANCH'."
 
@@ -420,7 +385,7 @@ v,verbose!        verbose (more) output
 "
 	local release_branches current_branch
 	local width branch len
-	local base develop_sha branch_sha nicename
+	local base master_sha branch_sha nicename
 
 	# cmd_default may already define flags
 	# at this stage we can not use parse_args
@@ -453,8 +418,8 @@ v,verbose!        verbose (more) output
 	width=$(($width+3-${#PREFIX}))
 
 	for branch in $release_branches; do
-		base=$(git merge-base "$branch" "$DEVELOP_BRANCH")
-		develop_sha=$(git rev-parse "$DEVELOP_BRANCH")
+		base=$(git merge-base "$branch" "$MASTER_BRANCH")
+		master_sha=$(git rev-parse "$MASTER_BRANCH")
 		branch_sha=$(git rev-parse "$branch")
 		if [ "$branch" = "$current_branch" ]; then
 			printf "* "
@@ -463,7 +428,7 @@ v,verbose!        verbose (more) output
 		fi
 		if flag verbose; then
 			printf "%-${width}s" "${branch#$PREFIX}"
-			if [ "$branch_sha" = "$develop_sha" ]; then
+			if [ "$branch_sha" = "$master_sha" ]; then
 				printf "(no commits yet)"
 			else
 				nicename=$(git rev-parse --short "$base")
@@ -514,20 +479,23 @@ Start a new release branch
 h,help!              Show this help
 showcommands!        Show git commands while executing them
 F,[no]fetch          Fetch from $ORIGIN before performing finish
+[no]publish        Publish this release after it is started
 v,verbose!           Verbose (more) output
 "
 	local base
 
 	# Define flags
 	DEFINE_boolean 'fetch' false "fetch from $ORIGIN before performing finish" F
+	DEFINE_boolean 'publish' true "publish this release after it is started"
 
 	# Override defaults with values from config
 	gitflow_override_flag_boolean   "release.start.fetch"   "fetch"
+	gitflow_override_flag_boolean   "release.start.publish" "publish"
 
 	# Parse arguments
 	parse_args "$@"
 	eval set -- "${FLAGS_ARGV}"
-	base=${2:-$DEVELOP_BRANCH}
+	base=${2:-$MASTER_BRANCH}
 
 	# Run filter on the version
 	VERSION=$(run_filter_hook release-start-version $VERSION)
@@ -542,7 +510,8 @@ v,verbose!           Verbose (more) output
 	gitflow_require_version_arg
 	gitflow_config_set_base_branch $base $BRANCH
 
-	require_no_existing_release_branches
+  # Removing requirement to only have one release branch
+	#require_no_existing_release_branches
 
 	# Sanity checks
 	require_clean_working_tree
@@ -574,6 +543,11 @@ v,verbose!           Verbose (more) output
 	echo
 	echo "     git flow release finish '$VERSION'"
 	echo
+
+  # Keeping both branches implies the --keep flag to be true.
+  if flag publish; then
+    cmd_publish $NAME
+  fi
 }
 
 cmd_finish() {
@@ -596,7 +570,7 @@ k,[no]keep          Keep branch after performing finish
 [no]keeplocal       Keep the local branch
 D,[no]force_delete  Force delete release branch after finish
 n,[no]tag           Don't tag this release
-b,[no]nobackmerge   Don't back-merge master, or tag if applicable, in develop
+b,[no]nobackmerge   Don't back-merge master, or tag if applicable, in master
 S,[no]squash        Squash release during merge
 "
 	# Define flags
@@ -605,13 +579,13 @@ S,[no]squash        Squash release during merge
 	DEFINE_string  'signingkey' "" "use the given GPG-key for the digital signature (implies -s)" u
 	DEFINE_string  'message' "" "use the given tag message" m
 	DEFINE_string  'messagefile' "" "use the contents of the given file as a tag message" f
-	DEFINE_boolean 'push' false "push to $ORIGIN after performing finish" p
+	DEFINE_boolean 'push' true "push to $ORIGIN after performing finish" p
 	DEFINE_boolean 'keep' false "keep branch after performing finish" k
 	DEFINE_boolean 'keepremote' false "keep the remote branch"
 	DEFINE_boolean 'keeplocal' false "keep the local branch"
 	DEFINE_boolean 'force_delete' false "force delete release branch after finish" D
 	DEFINE_boolean 'notag' false "don't tag this release" n
-	DEFINE_boolean 'nobackmerge' false "don't back-merge $MASTER_BRANCH, or tag if applicable, in $DEVELOP_BRANCH " b
+	DEFINE_boolean 'nobackmerge' false "don't back-merge $MASTER_BRANCH, or tag if applicable" b
 	DEFINE_boolean 'squash' false "squash release during merge" S
 	DEFINE_boolean 'squash-info' false "add branch info during squash"
 
@@ -649,7 +623,7 @@ S,[no]squash        Squash release during merge
 	BRANCH=$PREFIX$VERSION
 
 	BASE_BRANCH=$(gitflow_config_get_base_branch $BRANCH)
-	BASE_BRANCH=${BASE_BRANCH:-$DEVELOP_BRANCH}
+	BASE_BRANCH=${BASE_BRANCH:-$MASTER_BRANCH}
 	git_local_branch_exists "$BASE_BRANCH" || die "The base '$BASE_BRANCH' doesn't exists locally or is not a branch. Can't finish the release branch '$BRANCH'."
 
 	# Handle flags that imply other flags
@@ -673,8 +647,8 @@ S,[no]squash        Squash release during merge
 			git_fetch_branch "$ORIGIN" "$BRANCH"
 	fi
 
-	if [ "$BASE_BRANCH" = "$DEVELOP_BRANCH" ]; then
-		_finish_from_develop
+	if [ "$BASE_BRANCH" = "$MASTER_BRANCH" ]; then
+		_finish_from_master
 	else
 		_finish_base
 	fi
@@ -685,7 +659,7 @@ cmd_branch() {
 git flow release branch [-h] [-F] [-s] [-u] [-m] [-f] [-p] [-n] [-S] <version> [<name>]
 
 
-Release a branch [<name>], if a name is not given it defaults to the develop branch, and use the given version <version>
+Release a branch [<name>], if a name is not given it defaults to the master branch, and use the given version <version>
 --
 h,help              Show this help
 showcommands!       Show git commands while executing them
@@ -728,7 +702,7 @@ S,[no]squash 		Squash release during merge
 
 	# Read arguments into global variables
 	VERSION=$1
-	BRANCH=${2:-$DEVELOP_BRANCH}
+	BRANCH=${2:-$MASTER_BRANCH}
 
 	# Run filter on the version
 	VERSION=$(run_filter_hook branch-finish-version $VERSION)
@@ -947,7 +921,7 @@ p,[no]preserve-merges  Preserve merges
 	fi
 
 	BASE_BRANCH=$(gitflow_config_get_base_branch $BRANCH)
-	BASE_BRANCH=${BASE_BRANCH:-$DEVELOP_BRANCH}
+	BASE_BRANCH=${BASE_BRANCH:-$MASTER_BRANCH}
 
 	warn "Will try to rebase '$NAME' which is based on '$BASE_BRANCH'..."
 	require_clean_working_tree
@@ -997,13 +971,13 @@ r,[no]remote     Delete remote branch
 	run_pre_hook "$VERSION" "$ORIGIN" "$BRANCH"
 
 	current_branch=$(git_current_branch)
-	# We can't delete a branch we are on, switch to the develop branch.
+	# We can't delete a branch we are on, switch to the master branch.
 	if [ "$BRANCH" = "$current_branch" ]; then
 		require_clean_working_tree
-		git_do checkout "$DEVELOP_BRANCH" || die "Could not check out branch '$DEVELOP_BRANCH'."
+		git_do checkout "$MASTER_BRANCH" || die "Could not check out branch '$MASTER_BRANCH'."
 	fi
 
-	if ( git_is_branch_merged_into "$BRANCH" "$MASTER_BRANCH" && git_is_branch_merged_into "$BRANCH" "$DEVELOP_BRANCH" ); then
+	if ( git_is_branch_merged_into "$BRANCH" "$MASTER_BRANCH" ); then
 		git_do branch -d "$BRANCH" || die "Could not delete the $BRANCH."
 		if flag remote; then
 			git_do push "$ORIGIN" :"$BRANCH" || die "Could not delete the remote $BRANCH in $ORIGIN."
@@ -1015,7 +989,7 @@ r,[no]remote     Delete remote branch
 				git_do push "$ORIGIN" :"$BRANCH" || die "Could not delete the remote $BRANCH in $ORIGIN."
 			fi
 		else
-			die "Release branch '$BRANCH' has been not been merged in branch '$MASTER_BRANCH' and/or branch '$DEVELOP_BRANCH'. Use -f to force the deletion."
+			die "Release branch '$BRANCH' has been not been merged in branch '$MASTER_BRANCH'. Use -f to force the deletion."
 		fi
 	fi
 
diff --git a/gitflow-common b/gitflow-common
--- a/gitflow-common
+++ b/gitflow-common
@@ -74,6 +74,8 @@ max() { [ "$1" -ge "$2" ] && echo "$1" || echo "$2"; }
 # Basic string matching
 startswith() { [ "$1" != "${1#$2}" ]; }
 endswith() { [ "$1" != "${1%$2}" ]; }
+contains() { [ `echo "$1" | egrep -q "$2"; echo $?` -eq 0 ]; }
+notcontains() { [ `echo "$1" | egrep -q "$2"; echo $?` -ne 0 ]; }
 
 # Convenience functions for checking shFlags flags
 flag() { local FLAG; eval FLAG='$FLAGS_'$1; [ $FLAG -eq $FLAGS_TRUE ]; }
@@ -272,15 +274,9 @@ gitflow_has_master_configured() {
 	[ "$master" != "" ] && git_local_branch_exists "$master"
 }
 
-gitflow_has_develop_configured() {
-	local develop
-
-	develop=$(git config --get gitflow.branch.develop)
-	[ "$develop" != "" ] && git_local_branch_exists "$develop"
-}
-
 gitflow_has_prefixes_configured() {
 	git config --get gitflow.prefix.feature >/dev/null 2>&1     && \
+	git config --get gitflow.prefix.story >/dev/null 2>&1     && \
 	git config --get gitflow.prefix.release >/dev/null 2>&1     && \
 	git config --get gitflow.prefix.hotfix >/dev/null 2>&1      && \
 	git config --get gitflow.prefix.support >/dev/null 2>&1     && \
@@ -289,8 +285,6 @@ gitflow_has_prefixes_configured() {
 
 gitflow_is_initialized() {
 	gitflow_has_master_configured                    && \
-	gitflow_has_develop_configured                   && \
-	[ "$(git config --get gitflow.branch.master)" != "$(git config --get gitflow.branch.develop)" ] && \
 	gitflow_has_prefixes_configured
 }
 
@@ -298,10 +292,9 @@ gitflow_is_initialized() {
 gitflow_load_settings() {
 	export GIT_CURRENT_REPO_DIR="$(git rev-parse --show-toplevel 2>/dev/null)"
 	DOT_GIT_DIR=$(git rev-parse --git-dir)
-	export DOT_GIT_DIR=$(cd "$DOT_GIT_DIR" && pwd)
+	export DOT_GIT_DIR=$(cd "$DOT_GIT_DIR" 2>&1 1>/dev/null && pwd)
 	export HOOKS_DIR=$(git config --get gitflow.path.hooks || echo "$DOT_GIT_DIR"/hooks) # the second option is used to support previous versions of git-flow
 	export MASTER_BRANCH=$(git config --get gitflow.branch.master)
-	export DEVELOP_BRANCH=$(git config --get gitflow.branch.develop)
 	export ORIGIN=$(git config --get gitflow.origin || echo origin)
 
 	GITFLOW_CONFIG=$DOT_GIT_DIR/gitflow_config
@@ -499,6 +492,12 @@ gitflow_create_squash_message() {
 #
 # Parameter functions
 #
+gitflow_require_feature_arg() {
+	if [ "$FEATURE_NAME" = "" ]; then
+		die_help "Missing argument <feature>"
+	fi
+}
+
 gitflow_require_name_arg() {
 	if [ "$NAME" = "" ]; then
 		die_help "Missing argument <name>"
@@ -559,14 +558,34 @@ gitflow_use_current_branch_name() {
 
 	current_branch=$(git_current_branch)
 
-	if startswith "$current_branch" "$PREFIX"; then
+	if startswith "$current_branch" "$PREFIX" && notcontains "$current_branch" "story"; then
 		BRANCH=$current_branch
-		NAME=${BRANCH#$PREFIX}
+		NAME=`echo "$BRANCH" | sed -re "s@.*$PREFIX([^/]+).*@\1@g"`
+
+	elif contains "$current_branch" "$PREFIX" && [ "$SUBCOMMAND" = 'story' ]; then
+		BRANCH=$current_branch
+		NAME=`echo "$BRANCH" | sed -re "s@.*$PREFIX([^/]+).*@\1@g"`
+
 	else
-		warn "The current HEAD is no ${SUBCOMMAND} branch."
+		warn "The curent HEAD is no ${SUBCOMMAND} branch."
 		warn "Please specify a <name> argument."
 		exit 1
+
 	fi
+}
+
+gitflow_use_story_feature() {
+  local story_branches story_branch
+
+  story_branch=$(git_local_branches_prefixed "*/*/$PREFIX$NAME")
+  if [ -z $story_branch ]; then
+    warn "Unable to find the feature associated with this story"
+    exit 1
+  fi
+
+  FEATURE_NAME=`echo $story_branch | cut -d '/' -f 2`
+  FEATURE_BRANCH=$FEATURE_PREFIX$FEATURE_NAME
+  BRANCH=$FEATURE_BRANCH/$PREFIX$NAME
 }
 
 gitflow_use_current_branch_version() {
@@ -574,13 +593,19 @@ gitflow_use_current_branch_version() {
 
 	current_branch=$(git_current_branch)
 
-	if startswith "$current_branch" "$PREFIX"; then
+	if startswith "$current_branch" "$PREFIX" && notcontains "$current_branch" "story"; then
 		BRANCH=$current_branch
-		VERSION=${BRANCH#$PREFIX}
+		VERSION=`echo "$BRANCH" | sed -re "s@.*$PREFIX([^/]+).*@\1@g"`
+
+	elif contains "$current_branch" "$PREFIX" && [ "$SUBCOMMAND" = 'story' ]; then
+		BRANCH=$current_branch
+		VERSION=`echo "$BRANCH" | sed -re "s@.*$PREFIX([^/]+).*@\1@g"`
+
 	else
 		warn "The current HEAD is no ${SUBCOMMAND} branch."
 		warn "Please specify a <version> argument."
 		exit 1
+
 	fi
 }
 #
