WIP

diff --git a/git-flow-feature b/git-flow-feature
--- a/git-flow-feature
+++ b/git-flow-feature
@@ -179,15 +179,18 @@ Start new feature <name>, optionally basing it on <base> instead of <develop>
 --
 h,help!          Show this help
 showcommands!    Show git commands while executing them
-F,[no]fetch      Fetch from origin before performing local operation
+F,[no]fetch      Fetch from $ORIGIN before performing local operation
+[no]publish      Publish this feature after it is started
 "
 	local base
 
 	# Define flags
-	DEFINE_boolean 'fetch' false 'fetch from origin before performing local operation' F
+	DEFINE_boolean 'fetch' true 'fetch from $ORIGIN before performing local operation' F
+  DEFINE_boolean 'publish' true 'publish this feature after it is started'
 
 	# Override defaults with values from config
 	gitflow_override_flag_boolean   "feature.start.fetch"   "fetch"
+  gitflow_override_flag_boolean   "feature.start.publish" "publish"
 
 	# Parse arguments
 	parse_args "$@"
@@ -229,6 +232,14 @@ F,[no]fetch      Fetch from origin before performing local operation
 	echo ""
 	echo "     git flow feature finish $NAME"
 	echo
+
+  # Keeping both branches implies the --keep flag to be true.
+  if flag publish; then
+    orig_action=$SUBACTION
+    SUBACTION='publish'
+    cmd_publish $NAME
+    SUBACTION=$orig_action
+  fi
 }
 
 cmd_finish() {
@@ -239,9 +250,10 @@ Finish feature <name>
 --
 h,help!                Show this help
 showcommands!          Show git commands while executing them
-F,[no]fetch            Fetch from origin before performing finish
+F,[no]fetch            Fetch from $ORIGIN before performing finish
 r,[no]rebase           Rebase before merging
 p,[no]preserve-merges  Preserve merges while rebasing
+P,[no]push             Push to $ORIGIN after performing finish
 k,[no]keep             Keep branch after performing finish
 keepremote!        	   Keep the remote branch
 keeplocal!             Keep the local branch
@@ -255,6 +267,7 @@ no-ff!                 Never fast-forward during the merge
 	DEFINE_boolean 'fetch' false "fetch from $ORIGIN before performing finish" F
 	DEFINE_boolean 'rebase' false "rebase before merging" r
 	DEFINE_boolean 'preserve-merges' false 'try to recreate merges while rebasing' p
+  DEFINE_boolean 'push' true 'push to $ORIGIN after performing finish' P
 	DEFINE_boolean 'keep' false "keep branch after performing finish" k
 	DEFINE_boolean 'keepremote' false "keep the remote branch"
 	DEFINE_boolean 'keeplocal' false "keep the local branch"
@@ -267,6 +280,7 @@ no-ff!                 Never fast-forward during the merge
 	gitflow_override_flag_boolean   "feature.finish.fetch"             "fetch"
 	gitflow_override_flag_boolean   "feature.finish.rebase"            "rebase"
 	gitflow_override_flag_boolean   "feature.finish.preserve-merges"   "preserve_merges"
+  gitflow_override_flag_boolean   "feature.finish.push"              "push"
 	gitflow_override_flag_boolean   "feature.finish.keep"              "keep"
 	gitflow_override_flag_boolean   "feature.finish.keepremote"        "keepremote"
 	gitflow_override_flag_boolean   "feature.finish.keeplocal"         "keeplocal"
@@ -415,6 +429,9 @@ no-ff!                 Never fast-forward during the merge
 		exit 1
 	fi
 
+  if flag push; then
+    git_do push "$ORIGIN" "$BASE_BRANCH" || die "Could not push branch '$BASE_BRANCH' to remote '$ORIGIN'."
+  fi
 	run_post_hook "$NAME" "$ORIGIN" "$BRANCH"
 
 	# When no merge conflict is detected, just clean up the feature branch
@@ -485,6 +502,9 @@ helper_finish_cleanup() {
 		fi
 	fi
 	echo "- Feature branch '$BRANCH' "$keepmsg
+  if flag push; then
+    echo "- '$BASE_BRANCH' has been pushed to '$ORIGIN'"
+  fi
 	echo "- You are now on branch '$(git_current_branch)'"
 	echo
 }
